#!/usr/bin/env python3
"""Per-section word counter for manuscript.cls.

Copyright (c) 2026 Hayato Ishida
Released under the MIT License. See LICENSE-MIT.txt.

Reads a main .tex file, follows \\input and \\include, and writes
<jobname>.wcnt containing one \\mswc{<n>}{<count>} line per section
command in source order, plus three named totals:

    \\mswc{abstract}  the abstract, counted alone
    \\mswc{body}      everything up to the first unnumbered section
    \\mswc{total}     the whole document

The abstract is excluded from both body and total, since venues count it
separately and against its own limit.

manuscript.cls reads that file in draft mode and prints the count beside
each section heading and in the title block.

With --sections-from-aux it also writes <jobname>.rvw, the section list
review-form.tex needs, by reading the section entries LaTeX leaves in
<jobname>.aux. That makes the review form usable with any document class,
not just manuscript.cls, which writes its own .rvw and does not need this.

Because one script then owns both files, the count indices and the
section list cannot drift apart.

Usage:
    python3 wordcount.py main.tex
    python3 wordcount.py main.tex --sections-from-aux
"""

import os
import re
import sys

# Environments whose contents are not prose and should not be counted.
SKIP_ENVS = (
    "equation", "align", "gather", "multline", "flalign", "eqnarray",
    "tabular", "tabularx", "array", "figure", "table", "verbatim",
    "lstlisting", "tikzpicture", "thebibliography", "algorithmic",
)

INPUT_RE = re.compile(r"\\(?:input|include)\s*\{([^}]+)\}")

# Anything that puts a section-level heading on the page. \section and
# \section* carry prose and get a count. The rest are generated by LaTeX
# itself and carry none, but they still step the class's section counter,
# so they must reserve an index or every later count is attached to the
# wrong heading.
ABSTRACT_RE = re.compile(r"\\begin\{abstract\}(.*?)\\end\{abstract\}",
                         re.DOTALL)

HEADING_RE = re.compile(
    r"\\section\*?\s*(?:\[[^\]]*\])?\s*\{"
    r"|\\bibliography\s*\{"
    r"|\\printbibliography"
    r"|\\tableofcontents"
    r"|\\listoffigures"
    r"|\\listoftables"
)


def strip_comments(text):
    """Remove % comments, keeping escaped \\%."""
    out = []
    for line in text.split("\n"):
        result = []
        i = 0
        while i < len(line):
            ch = line[i]
            if ch == "\\" and i + 1 < len(line):
                result.append(line[i:i + 2])
                i += 2
                continue
            if ch == "%":
                break
            result.append(ch)
            i += 1
        out.append("".join(result))
    return "\n".join(out)


def expand(path, seen):
    """Return the source of `path` with \\input/\\include expanded inline."""
    real = os.path.realpath(path)
    if real in seen:
        return ""
    seen.add(real)
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError:
        return ""
    text = strip_comments(text)

    base = os.path.dirname(path)

    def replace(match):
        target = match.group(1).strip()
        if not target.endswith(".tex"):
            target = target + ".tex"
        return expand(os.path.join(base, target), seen)

    return INPUT_RE.sub(replace, text)


def body_only(text):
    """Drop the preamble and anything after \\end{document}."""
    start = text.find(r"\begin{document}")
    if start != -1:
        text = text[start + len(r"\begin{document}"):]
    end = text.find(r"\end{document}")
    if end != -1:
        text = text[:end]
    return text


def count_words(chunk):
    """Count prose words in a chunk of LaTeX, ignoring maths and floats."""
    for env in SKIP_ENVS:
        chunk = re.sub(
            r"\\begin\{" + env + r"\*?\}.*?\\end\{" + env + r"\*?\}",
            " ", chunk, flags=re.DOTALL,
        )
    chunk = re.sub(r"\\\[.*?\\\]", " ", chunk, flags=re.DOTALL)
    chunk = re.sub(r"\$\$.*?\$\$", " ", chunk, flags=re.DOTALL)
    chunk = re.sub(r"\$[^$]*\$", " ", chunk)

    # Commands that swallow their argument entirely.
    chunk = re.sub(r"\\(?:label|ref|cref|Cref|eqref|cite[a-zA-Z]*|includegraphics"
                   r"|bibliography|bibliographystyle|usepackage|documentclass"
                   r"|input|include|hypersetup|url|href)\s*(?:\[[^\]]*\])?"
                   r"\s*\{[^}]*\}", " ", chunk)
    # Remaining control sequences.
    chunk = re.sub(r"\\[a-zA-Z@]+\*?", " ", chunk)
    chunk = re.sub(r"\\.", " ", chunk)
    chunk = re.sub(r"[{}\[\]&~^_]", " ", chunk)

    return sum(1 for token in chunk.split() if re.search(r"[A-Za-z]", token))


def read_group(text, start):
    """Read a brace-balanced {...} group beginning at `start`.

    Returns (contents, index just past the closing brace), or (None, start)
    if `start` is not an opening brace. A regex cannot do this: section
    titles routinely contain braces of their own.
    """
    if start >= len(text) or text[start] != "{":
        return None, start
    depth = 0
    i = start
    while i < len(text):
        if text[i] == "\\":       # skip an escaped character
            i += 2
            continue
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i + 1
        i += 1
    return None, start


def tidy_title(raw):
    """Turn a .aux section title into something printable on a form."""
    number = ""
    match = re.match(r"\s*\\numberline\s*", raw)
    if match:
        number, after = read_group(raw, match.end())
        raw = raw[after:] if number is not None else raw[match.end():]
        number = (number or "").strip()

    # \texorpdfstring{tex}{pdf} keeps the first argument.
    while True:
        match = re.search(r"\\texorpdfstring\s*", raw)
        if not match:
            break
        first, after = read_group(raw, match.end())
        if first is None:
            break
        _, after = read_group(raw, after)
        raw = raw[:match.start()] + first + raw[after:]

    raw = re.sub(r"\\[a-zA-Z@]+\s*", "", raw)
    raw = raw.replace("{", "").replace("}", "").replace("~", " ")
    return number, " ".join(raw.split())


def sections_from_aux(aux_path):
    """Section number, title and page for each \\section in a .aux file.

    Every class that uses a standard \\section writes these, whether or not
    the document prints a table of contents, so this works far beyond
    manuscript.cls. Starred sections are absent, since they add nothing to
    the contents.
    """
    try:
        with open(aux_path, encoding="utf-8", errors="replace") as handle:
            aux = handle.read()
    except OSError:
        return []

    found = []
    for match in re.finditer(r"\\contentsline\s*", aux):
        kind, after = read_group(aux, match.end())
        if kind != "section":
            continue
        raw_title, after = read_group(aux, after)
        page, after = read_group(aux, after)
        if raw_title is None or page is None:
            continue
        number, title = tidy_title(raw_title)
        found.append((number, title, " ".join(page.split())))
    return found


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    if len(args) != 1 or flags - {"--sections-from-aux"}:
        print("usage: wordcount.py <main.tex> [--sections-from-aux]",
              file=sys.stderr)
        return 2
    sys.argv = [sys.argv[0], args[0]]

    source = sys.argv[1]
    if not os.path.exists(source):
        print("wordcount.py: no such file: " + source, file=sys.stderr)
        return 1

    text = body_only(expand(source, set()))

    # The abstract is counted on its own and then removed, so it lands in
    # neither the body subtotal nor the total. Venues count it separately
    # and against its own limit, so folding it in would only mislead.
    abstract = 0
    found = ABSTRACT_RE.search(text)
    if found:
        abstract = count_words(found.group(1))
        text = text[:found.start()] + " " + text[found.end():]

    # Every heading in source order, so the indices line up with the
    # counter the class steps at each formatted heading.
    heads = []
    for match in HEADING_RE.finditer(text):
        token = match.group(0)
        is_section = token.startswith("\\section")
        is_starred = is_section and "*" in token
        heads.append((match.start(), is_section, is_starred))
    bounds = [start for start, _, _ in heads] + [len(text)]

    lines = []
    total = 0
    body = 0
    counted = 0
    in_body = True
    numbered = []   # indices of numbered sections, in document order
    for index, (begin, is_section, is_starred) in enumerate(heads, start=1):
        if is_starred:
            # Acknowledgements and the like end the body proper. Everything
            # from here on is back matter and is left out of the subtotal.
            in_body = False
        if not is_section:
            continue  # reserve the index, emit nothing, so no tag is drawn
        if not is_starred:
            # Only these reach the .aux, so only these can be paired with
            # its entries later.
            numbered.append(index)
        count = count_words(text[begin:bounds[index]])
        total += count
        if in_body:
            body += count
        counted += 1
        lines.append("\\mswc{%d}{%d}" % (index, count))

    if heads:
        preamble_words = count_words(text[:heads[0][0]])
    else:
        preamble_words = count_words(text)
    total += preamble_words
    body += preamble_words

    lines.append("\\mswc{abstract}{%d}" % abstract)
    lines.append("\\mswc{body}{%d}" % body)
    lines.append("\\mswc{total}{%d}" % total)

    out = os.path.splitext(source)[0] + ".wcnt"
    with open(out, "w", encoding="utf-8") as handle:
        handle.write("%% generated by wordcount.py -- do not edit\n")
        handle.write("\n".join(lines) + "\n")

    print("wordcount.py: %d sections, %d words (+%d abstract) -> %s"
          % (counted, total, abstract, os.path.basename(out)))

    if "--sections-from-aux" in flags:
        base = os.path.splitext(source)[0]
        entries = sections_from_aux(base + ".aux")
        if not entries:
            print("wordcount.py: no section entries in %s.aux, so no .rvw "
                  "was written. Build the document first."
                  % os.path.basename(base), file=sys.stderr)
            return 1
        if len(entries) != len(numbered):
            print("wordcount.py: %d sections in the source but %d in the "
                  ".aux; pairing the first %d. Word counts past that point "
                  "may sit on the wrong row."
                  % (len(numbered), len(entries),
                     min(len(entries), len(numbered))), file=sys.stderr)

        rvw = base + ".rvw"
        with open(rvw, "w", encoding="utf-8") as handle:
            handle.write("%% generated by wordcount.py -- do not edit\n")
            for position, (number, title, page) in enumerate(entries):
                if position >= len(numbered):
                    break
                # The trailing percent comments out the newline. Without it
                # each line yields a space token, and a space between two
                # rows of a table opens a row of its own.
                handle.write("\\rvwsection{%d}{%s}{%s}{%s}%%\n"
                             % (numbered[position], number, title, page))
        print("wordcount.py: %d sections from .aux -> %s"
              % (min(len(entries), len(numbered)), os.path.basename(rvw)))

    return 0


if __name__ == "__main__":
    sys.exit(main())
