#!/usr/bin/env python3
"""Per-section word counter for manuscript.cls.

Copyright (c) 2026 Hayato Ishida
Released under the MIT License. See LICENSE-MIT.txt.

Reads a main .tex file, follows \\input and \\include, and writes
<jobname>.wcnt containing one \\mswc{<n>}{<count>} line per section
command in source order, plus \\mswc{total}{<count>}.

manuscript.cls reads that file in draft mode and prints the count beside
each section heading and in the title block.

Usage:
    python3 wordcount.py main.tex
"""

import os
import re
import sys

# Environments whose contents are not prose and should not be counted.
SKIP_ENVS = (
    "equation", "align", "gather", "multline", "flalign", "eqnarray",
    "tabular", "tabularx", "array", "figure", "table", "verbatim",
    "lstlisting", "tikzpicture", "thebibliography", "algorithmic",
)

INPUT_RE = re.compile(r"\\(?:input|include)\s*\{([^}]+)\}")

# Anything that puts a section-level heading on the page. \section and
# \section* carry prose and get a count. The rest are generated by LaTeX
# itself and carry none, but they still step the class's section counter,
# so they must reserve an index or every later count is attached to the
# wrong heading.
HEADING_RE = re.compile(
    r"\\section\*?\s*(?:\[[^\]]*\])?\s*\{"
    r"|\\bibliography\s*\{"
    r"|\\printbibliography"
    r"|\\tableofcontents"
    r"|\\listoffigures"
    r"|\\listoftables"
)


def strip_comments(text):
    """Remove % comments, keeping escaped \\%."""
    out = []
    for line in text.split("\n"):
        result = []
        i = 0
        while i < len(line):
            ch = line[i]
            if ch == "\\" and i + 1 < len(line):
                result.append(line[i:i + 2])
                i += 2
                continue
            if ch == "%":
                break
            result.append(ch)
            i += 1
        out.append("".join(result))
    return "\n".join(out)


def expand(path, seen):
    """Return the source of `path` with \\input/\\include expanded inline."""
    real = os.path.realpath(path)
    if real in seen:
        return ""
    seen.add(real)
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError:
        return ""
    text = strip_comments(text)

    base = os.path.dirname(path)

    def replace(match):
        target = match.group(1).strip()
        if not target.endswith(".tex"):
            target = target + ".tex"
        return expand(os.path.join(base, target), seen)

    return INPUT_RE.sub(replace, text)


def body_only(text):
    """Drop the preamble and anything after \\end{document}."""
    start = text.find(r"\begin{document}")
    if start != -1:
        text = text[start + len(r"\begin{document}"):]
    end = text.find(r"\end{document}")
    if end != -1:
        text = text[:end]
    return text


def count_words(chunk):
    """Count prose words in a chunk of LaTeX, ignoring maths and floats."""
    for env in SKIP_ENVS:
        chunk = re.sub(
            r"\\begin\{" + env + r"\*?\}.*?\\end\{" + env + r"\*?\}",
            " ", chunk, flags=re.DOTALL,
        )
    chunk = re.sub(r"\\\[.*?\\\]", " ", chunk, flags=re.DOTALL)
    chunk = re.sub(r"\$\$.*?\$\$", " ", chunk, flags=re.DOTALL)
    chunk = re.sub(r"\$[^$]*\$", " ", chunk)

    # Commands that swallow their argument entirely.
    chunk = re.sub(r"\\(?:label|ref|cref|Cref|eqref|cite[a-zA-Z]*|includegraphics"
                   r"|bibliography|bibliographystyle|usepackage|documentclass"
                   r"|input|include|hypersetup|url|href)\s*(?:\[[^\]]*\])?"
                   r"\s*\{[^}]*\}", " ", chunk)
    # Remaining control sequences.
    chunk = re.sub(r"\\[a-zA-Z@]+\*?", " ", chunk)
    chunk = re.sub(r"\\.", " ", chunk)
    chunk = re.sub(r"[{}\[\]&~^_]", " ", chunk)

    return sum(1 for token in chunk.split() if re.search(r"[A-Za-z]", token))


def main():
    if len(sys.argv) != 2:
        print("usage: wordcount.py <main.tex>", file=sys.stderr)
        return 2

    source = sys.argv[1]
    if not os.path.exists(source):
        print("wordcount.py: no such file: " + source, file=sys.stderr)
        return 1

    text = body_only(expand(source, set()))

    # Every heading in source order, so the indices line up with the
    # counter the class steps at each formatted heading.
    heads = []
    for match in HEADING_RE.finditer(text):
        token = match.group(0)
        is_section = token.startswith("\\section")
        is_starred = is_section and "*" in token
        heads.append((match.start(), is_section, is_starred))
    bounds = [start for start, _, _ in heads] + [len(text)]

    lines = []
    total = 0
    body = 0
    counted = 0
    in_body = True
    for index, (begin, is_section, is_starred) in enumerate(heads, start=1):
        if is_starred:
            # Acknowledgements and the like end the body proper. Everything
            # from here on is back matter and is left out of the subtotal.
            in_body = False
        if not is_section:
            continue  # reserve the index, emit nothing, so no tag is drawn
        count = count_words(text[begin:bounds[index]])
        total += count
        if in_body:
            body += count
        counted += 1
        lines.append("\\mswc{%d}{%d}" % (index, count))

    if heads:
        preamble_words = count_words(text[:heads[0][0]])
    else:
        preamble_words = count_words(text)
    total += preamble_words
    body += preamble_words

    lines.append("\\mswc{body}{%d}" % body)

    lines.append("\\mswc{total}{%d}" % total)

    out = os.path.splitext(source)[0] + ".wcnt"
    with open(out, "w", encoding="utf-8") as handle:
        handle.write("%% generated by wordcount.py -- do not edit\n")
        handle.write("\n".join(lines) + "\n")

    print("wordcount.py: %d sections, %d words -> %s"
          % (counted, total, os.path.basename(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
